name: Python

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.12"]
        rye-version: ["latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: narumiruna/setup-rye-action@v1.2.0
        with:
            version: ${{ matrix.rye-version }}
            cache: true
      - name: Install dependencies
        run: rye sync
      - name: Lint
        run: rye check .
      - name: Type check
        run: rye run mypy --install-types --non-interactive .
      - name: Test
        run: rye run pytest -v -s --cov=src --cov-report=xml tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
